@echo off 
call 3.run.bat out\1.Hello.lct_asm.txt out\1.Hello.lct_asm.obj
call 3.run.bat out\2.localVarTest.lct_asm.txt out\2.localVarTest.lct_asm.obj
call 3.run.bat out\3.strings.lct_asm.txt out\3.strings.lct_asm.obj
call 3.run.bat out\4.functions.lct_asm.txt out\4.functions.lct_asm.obj
call 3.run.bat out\5.params-int.lct_asm.txt out\5.params-int.lct_asm.obj
call 3.run.bat out\7.params-int-LET.lct_asm.txt out\7.params-int-LET.lct_asm.obj
call 3.run.bat out\8.params-int-LETR.lct_asm.txt out\8.params-int-LETR.lct_asm.obj
call 3.run.bat out\9.arithmetic.lct_asm.txt out\9.arithmetic.lct_asm.obj
call 3.run.bat out\11.IF-Else.lct_asm.txt out\11.IF-Else.lct_asm.obj
call 3.run.bat out\12.SimpleNestedIF.lct_asm.txt out\12.SimpleNestedIF.lct_asm.obj
call 3.run.bat out\13.paramTest.lct_asm.txt out\13.paramTest.lct_asm.obj
call 3.run.bat out\14.paramLoop.lct_asm.txt out\14.paramLoop.lct_asm.obj
call 3.run.bat out\15.doLoop.lct_asm.txt out\15.doLoop.lct_asm.obj
call 3.run.bat out\15b.print50.lct_asm.txt out\15b.print50.lct_asm.obj
call 3.run.bat out\15c.fibonacci.lct_asm.txt out\15c.fibonacci.lct_asm.obj
call 3.run.bat out\15d.fibonacci.lct_asm.txt out\15d.fibonacci.lct_asm.obj
call 3.run.bat out\17a.global.lct_asm.txt out\17a.global.lct_asm.obj
call 3.run.bat out\17b.gbLoop.lct_asm.txt out\17b.gbLoop.lct_asm.obj
call 3.run.bat out\bug2.whileLoop.lct_asm.txt out\bug2.whileLoop.lct_asm.obj
call 3.run.bat out\16.recursion.lct_asm.txt out\16.recursion.lct_asm.obj
call 3.run.bat out\16b.addtorial.lct_asm.txt out\16b.addtorial.lct_asm.obj
call 3.run.bat out\16d.factorial.lct_asm.txt out\16d.factorial.lct_asm.obj
call 3.run.bat out\reg.lct_asm.txt out\reg.lct_asm.obj
call 3.run.bat out\divA.lct_asm.txt out\divA.lct_asm.obj
call 3.run.bat out\rawPrint.lct_asm.txt out\rawPrint.lct_asm.obj
call 3.run.bat out\pointerA.lct_asm.txt out\pointerA.lct_asm.obj
call 3.run.bat out\pointerBprint.lct_asm.txt out\pointerBprint.lct_asm.obj
call 3.run.bat out\strcpy.lct_asm.txt out\strcpy.lct_asm.obj
call 3.run.bat out\strswap.lct_asm.txt out\strswap.lct_asm.obj
call 3.run.bat out\str-reverse.lct_asm.txt out\str-reverse.lct_asm.obj
call 3.run.bat out\15e.nestedLoop.lct_asm.txt out\15e.nestedLoop.lct_asm.obj
call 3.run.bat out\arraysort.lct_asm.txt out\arraysort.lct_asm.obj